rules:
  - name: Account-Linking-Extension
    script: ./rules/Account-Linking-Extension.js
    stage: login_success
    enabled: false
    order: 20
  - name: Common-Functions
    script: ./rules/Common-Functions.js
    stage: login_success
    enabled: true
    order: 0
  - name: Contextual-MFA-Step-UP
    script: ./rules/Contextual-MFA-Step-UP.js
    stage: login_success
    enabled: false
    order: 2
  - name: Enrich-Profile-from-Clearbit
    script: ./rules/Enrich-Profile-from-Clearbit.js
    stage: login_success
    enabled: false
    order: 21
  - name: Enroll-MFA
    script: ./rules/Enroll-MFA.js
    stage: login_success
    enabled: true
    order: 1
  - name: Migration
    script: ./rules/Migration.js
    stage: login_success
    enabled: true
    order: 10
rulesConfigs: []
hooks: []
pages:
  - name: login
    enabled: false
    html: ./pages/login.html
resourceServers:
  - name: Travel0 API
    identifier: https://legacy-demo-test-travel0.auth0.cloud/api
    allow_offline_access: false
    scopes:
      - value: read:payment
        description: Read payment methods
      - value: update:payment
        description: Update payment methods
      - value: approve:travel
        description: Can approve travel for corporate users
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_dialect: access_token_authz
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: Service0
    app_type: non_interactive
    client_secret: DdhecduvB4GcLp0de69nLGFQIyAtNVis5SGl4-UItu4YduFe0urSxd_17ImHKKIw
    cross_origin_auth: false
    custom_login_page_on: true
    description: Service client that performs various user related tasks
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
  - name: Travel0 Consumer Website
    allowed_clients: []
    allowed_logout_urls:
      - https://legacy-demo-test.auth0.cloud
    app_type: spa
    callbacks:
      - https://legacy-demo-test.auth0.cloud
      - https://legacy-demo-test.auth0.cloud/payment
    client_aliases: []
    client_metadata:
      demoTemplate: travel0
      name: default
      userApp: 'true'
    client_secret: Lreo-c5o8crZc1BD6sRHDYs8Eubr49nPjtyFHgP3Bsc7gE-jOJwrdX2SUeM81f8-
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - https://legacy-demo-test.auth0.cloud
      - https://legacy-demo-test.auth0.cloud/payment
  - name: Travel0 Corporate Website
    allowed_clients: []
    allowed_logout_urls:
      - https://legacy-demo-test-corporate.auth0.cloud
    allowed_origins:
      - https://legacy-demo-test-corporate.auth0.cloud
    app_type: spa
    callbacks:
      - https://legacy-demo-test-corporate.auth0.cloud
    client_aliases: []
    client_metadata:
      demoTemplate: travel0
      name: corporate
      userApp: 'true'
    client_secret: 2YihhZRWzps9Yz-16py0C7AFAgvVmDMQldbUPHFj16Ldt4w-eOCfALvpeWaBLGcJ
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - https://legacy-demo-test-corporate.auth0.cloud
  - name: Travel0 Cruise Website
    allowed_clients: []
    allowed_logout_urls:
      - https://legacy-demo-test-cruise.auth0.cloud
    allowed_origins:
      - https://legacy-demo-test-cruise.auth0.cloud
    app_type: spa
    callbacks:
      - https://legacy-demo-test-cruise.auth0.cloud
    client_aliases: []
    client_metadata:
      demoTemplate: travel0
      name: cruise
    client_secret: EHV_m7MNuTXIAhczX-A6Oyd-eIyfBya0YCFK7cpnCAyAs03VNmtzqb-ZGVbTz9MU
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - https://legacy-demo-test-cruise.auth0.cloud
  - name: Travel0 M2M Client
    app_type: non_interactive
    client_metadata:
      demoTemplate: travel0
      name: default
    client_secret: tSOFI3QN_IYCRcLy7ELYAynk38XN_CJxOE6OovFOpz75KU9qdiUVnJDy9HjF-v2T
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: demo-platform-deployer
    client_secret: JrcqiqPuMGPtU1muDhLLc0pvKNysnpECVcpX5a_2C6KoTZKgNfPq7LVD-YLOvfYI
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: false
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
databases:
  - name: consumer-users
    strategy: auth0
    enabled_clients:
      - Travel0 Consumer Website
      - Travel0 Cruise Website
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      validation:
        username:
          max: 15
          min: 1
      import_mode: true
      customScripts:
        get_user: ./databases/consumer-users/get_user.js
        login: ./databases/consumer-users/login.js
      disable_signup: false
      passwordPolicy: good
      strategy_version: 2
      requires_username: false
      brute_force_protection: true
      enabledDatabaseCustomization: true
    realms:
      - consumer-database-connection
      - consumer-users
  - name: corporate-users
    strategy: auth0
    enabled_clients:
      - Travel0 Corporate Website
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      validation:
        username:
          max: 15
          min: 1
      disable_signup: false
      passwordPolicy: good
      strategy_version: 2
      requires_username: false
      brute_force_protection: true
    realms:
      - corporate-database-connection
      - corporate-users
connections:
  - name: facebook
    strategy: facebook
    enabled_clients: []
    is_domain_connection: false
    options:
      email: true
      scope: email
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients: []
    is_domain_connection: false
    options:
      email: true
      gmail: false
      orkut: false
      scope:
        - email
        - profile
      sites: false
      tasks: false
      blogger: false
      profile: true
      youtube: false
      calendar: false
      contacts: false
      analytics: false
      client_id: ''
      moderator: false
      coordinate: false
      picasa_web: false
      google_plus: false
      google_books: false
      google_drive: false
      spreadsheets: false
      document_list: false
      latitude_best: false
      latitude_city: false
      url_shortener: false
      webmaster_tools: false
      chrome_web_store: false
      allowed_audiences: ''
      adsense_management: false
      google_drive_files: false
      coordinate_readonly: false
      google_cloud_storage: false
      content_api_for_shopping: false
      google_affiliate_network: false
  - name: hooli-waad
    strategy: waad
    display_name: Hooli directory
    enabled_clients:
      - Travel0 Corporate Website
    is_domain_connection: false
    options:
      domain: hooli.company
      client_id: 08fe99e1-ea84-44b8-840b-cb7e1722a9d6
      use_wsfed: false
      ext_groups: true
      ext_profile: true
      identity_api: microsoft-identity-platform-v2.0
      basic_profile: false
      client_secret: 7E-8Q~9IfRgBpFhmjlNQlyLCGgYXszcnRWvIIb2i
      tenant_domain: hooli.company
      waad_protocol: openid-connect
      api_enable_users: true
      ext_nested_groups: false
      useCommonEndpoint: false
      should_trust_email_verified_connection: never_set_emails_as_verified
    show_as_button: true
tenant:
  enabled_locales:
    - en
  flags:
    new_universal_login_experience_enabled: false
    universal_login: true
    dashboard_ui_next: true
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: TravelZero
  picture_url: https://cdn.staging.auth0.cloud/assets/icons/TravelZero-avatar.png
  universal_login:
    colors:
      page_background: '#FF7F38'
      primary: '#FF7F38'
emailProvider:
  name: smtp
  credentials:
    smtp_host: smtp.mailtrap.io
    smtp_port: 25
    smtp_user: 4f8df227b826b1
    smtp_pass: '##SMTP_PASS##'
  default_from_address: no-reply@auth0user.net
  enabled: true
emailTemplates:
  - template: reset_email
    body: ./emailTemplates/reset_email.html
    enabled: true
    from: Travel0 Accounts <accounts@travel0.net>
    subject: ''
    syntax: liquid
    urlLifetimeInSeconds: 432000
  - template: verify_email
    body: ./emailTemplates/verify_email.html
    enabled: true
    from: Travel0 Accounts <accounts@travel0.net>
    resultUrl: https://legacy-demo-test.auth0.cloud
    subject: ''
    syntax: liquid
    urlLifetimeInSeconds: 432000
  - template: welcome_email
    body: ./emailTemplates/welcome_email.html
    enabled: true
    from: Travel0 Accounts <accounts@travel0.net>
    subject: Welcome to Travel0
    syntax: liquid
clientGrants:
  - client_id: Service0
    audience: https://julian-new.demo-platform.auth0app.com/api/v2/
    scope:
      - read:users
      - update:users
      - create:users
      - delete:users
      - read:roles
      - update:roles
      - read:connections
      - read:rules
      - create:rules
      - update:rules
      - delete:rules
      - read:clients
      - delete:clients
      - read:resource_servers
      - 'update:resource_servers '
      - delete:resource_servers
      - read:guardian_enrollments
      - read:guardian_factors
      - read:logs
      - read:device_credentials
      - update:device_credentials
      - delete:device_credentials
      - delete:guardian_enrollments
      - create:clients
      - read:client_keys
      - update:clients
  - client_id: Travel0 M2M Client
    audience: https://julian-new.demo-platform.auth0app.com/api/v2/
    scope:
      - read:users
      - update:users
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: true
  - name: push-notification
    enabled: true
  - name: recovery-code
    enabled: true
  - name: sms
    enabled: true
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders:
  - name: sms
    auth_token: d69a9130ec4020e32237d3a893b04f91
    from: null
    messaging_service_sid: MGbcbefbf8e5c2ff1aa3760a08a1962d42
    provider: twilio
    sid: AC96e5ba5cdd4afe918cff24fe32c369af
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: twilio
guardianPhoneFactorMessageTypes:
  message_types:
    - sms
roles:
  - name: Travel Approver
    description: Can approve travel
    permissions:
      - permission_name: approve:travel
        resource_server_identifier: https://legacy-demo-test-travel0.auth0.cloud/api
branding:
  colors:
    page_background: '#FF7F38'
    primary: '#FF7F38'
  logo_url: https://cdn.staging.auth0.cloud/assets/icons/TravelZero-avatar.png
  templates: []
prompts:
  customText: {}
  identifier_first: false
  universal_login_experience: new
  webauthn_platform_first_factor: false
migrations:
  legacy_custom_claims: true
  role_users_offset_pagination_over_thousand: true
actions: []
triggers: {}
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: true
    shields:
      - block
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams:
  - name: Okta Demo Engineering Logging
    filters:
      - type: category
        name: auth.login.success
      - type: category
        name: auth.silent_auth.success
      - type: category
        name: auth.token_exchange.success
      - type: category
        name: user.success
      - type: category
        name: user.notification
      - type: category
        name: auth.signup.success
      - type: category
        name: management.success
      - type: category
        name: other
      - type: category
        name: auth.logout.success
    sink:
      httpContentFormat: JSONARRAY
      httpContentType: application/json
      httpEndpoint: https://events.oktademo.engineering/logs
    status: active
    type: http
customDomains:
  - domain: julian-new.algorox.com
    primary: true
    status: ready
    tls_policy: recommended
    type: auth0_managed_certs
    verification:
      methods:
        - name: cname
          record: >-
            julian-new-cd-ur5khsmerg77cuws.edge.tenants.demo-platform.auth0app.com
themes:
  - borders:
      button_border_weight: 1
      buttons_style: pill
      button_border_radius: 3
      input_border_weight: 1
      inputs_style: rounded
      input_border_radius: 9
      widget_corner_radius: 32
      widget_border_weight: 0
      show_widget_shadow: true
    colors:
      primary_button: '#FF7F38'
      primary_button_label: '#ffffff'
      secondary_button_border: '#c2c8d0'
      secondary_button_label: '#2d333a'
      base_focus_color: '#635dff'
      base_hover_color: '#000000'
      links_focused_components: '#007bad'
      header: '#2d333a'
      body_text: '#2d333a'
      widget_background: '#ffffff'
      widget_border: '#c2c8d0'
      input_labels_placeholders: '#6f7780'
      input_filled_text: '#000000'
      input_border: '#c2c8d0'
      input_background: '#ffffff'
      icons: '#6f7780'
      error: '#d00e17'
      success: '#0a8852'
    displayName: Unnamed Theme
    fonts:
      font_url: ''
      reference_text_size: 16
      title:
        bold: false
        size: 150
      subtitle:
        bold: false
        size: 87.5
      body_text:
        bold: false
        size: 87.5
      buttons_text:
        bold: false
        size: 100
      input_labels:
        bold: false
        size: 100
      links:
        bold: true
        size: 87.5
      links_style: normal
    page_background:
      page_layout: center
      background_color: '#000000'
      background_image_url: https://cdn.staging.auth0.cloud/assets/imgs/TravelZero-Background.jpg
    widget:
      logo_position: center
      logo_url: https://cdn.staging.auth0.cloud/assets/icons/TravelZeroLogoColor.png
      logo_height: 60
      header_text_alignment: center
      social_buttons_layout: bottom
